version: '2'
services:
  mysql:
      image: mysql:latest
      ports:
        - "3306:3306"
      restart: always
      environment:
          MYSQL_DATABASE: 'security'
          # So you don't have to use root, but you can if you like
          MYSQL_USER: 'root'
          # You can use whatever password you like
          MYSQL_PASSWORD: 'root'
          # Password for root access
          MYSQL_ROOT_PASSWORD: 'root'

      expose:
        # Opens port 3306 on the container
        - '3306'


  authentication:
    build:
      context: JWTauthentication
      dockerfile: Dockerfile
   
    restart: always
    ports:
      - "8098:8098"
    network_mode: host
    depends_on: 
      - mysql
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/security?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false

  serving:
    build:
      context: serving2/serving2
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    ports:
      - "8051:8051"
  

  random-recommandation:
    build:
      context: random-recommandation-service
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    ports:
      - "8049:8049"
